### ISSUE TITLE
Understandability improvement

### ISSUE THREAD

**Issue by pjljvandelaar** [zertovitch/zip-ada#2]
Dear Developers,

Why is on line
https://github.com/zertovitch/zip-ada/blob/8c5d56b3a87ed77066de0b321e8e6ebd48aa3087/zip_lib/lzma-encoding.adb#L351
a constant introduced that is only used once?

Why is the division not just executed on its usage?

Greetings,
   Pierre

**Comment by zertovitch** [comment]
Dear Pierre,
On most processors, divisions are a lot slower that multiplications (*). So I let it done at compile-time.
Cheers,
Gautier
___
(*) by a factor ~10, on various processors, since decades, for floats and integers alike.

**Comment by zertovitch** [comment]
Added a comment about that (cbc8eb175eefba7c57df71a55f0c1b80c72c7f9b).
