### ISSUE TITLE
Why x + x in lzma-decoding.adb?

### ISSUE THREAD

**Issue by pjljvandelaar** [zertovitch/zip-ada#3]
Dear developers,

In lzma-decoding.adb I am puzzled by a number of statements like https://github.com/zertovitch/zip-ada/blob/8886ffffa4b57300f7a21064baa1abaf8251ac89/zip_lib/lzma-decoding.adb#L281
Why do they contain x + x instead of 2*x?
Is it due to the translation from C(pp), since Ada doesn't have the `+=` increment assignment operator and so ` x += x + a;` is translated to `x := x + x + a; `? 
Is it due to performance reasons, which would surprise me since normally using both `+` and `*` results in faster code?
Or is there even another reason?

Thanks in advance for your clarification!

Pierre

**Comment by zertovitch** [comment]
It's not due to a translation of `+=`: the corresponding instruction in LzmaSpec.cpp is `m = (m << 1) + rc->DecodeBit(&Probs[m]);`, so probably it's a dumb GCC-tweaking optimization that might have worked at the time of the translation...

**Comment by zertovitch** [comment]
The assembler output of `gcc -S -O2 -gnatp -fno-inline unzip-decompress.adb` is (fortunately) identical with x + x vs. 2 * x.
Tested with GNAT CE 2021 Win64 and GNAT GPL 2017 Win32.
Thanks for the spotting that!
