### ISSUE TITLE
Why this order?

### ISSUE THREAD

**Issue by pjljvandelaar** [zertovitch/zip-ada#4]
When searching for atypical patterns in Ada code.
I found an instance of the atypical pattern `var := cond or else var;`
on the following line: https://github.com/zertovitch/zip-ada/blob/35652d6ef7d558c4f6a353c6f965a2dd39a002a8/zip_lib/lzma-decoding.adb#L339

Why do you use this pattern?
There is no side effect in the condition `will_fill`, so would the typical pattern `var := var or else cond;` not only result in more typical but also potential faster code?

Thanks in advance for your answer!

Pierre

**Comment by zertovitch** [comment]
There is no good reason for that. It looks like the remnant of something else. This fixed now.
I've also replaced "`or else`" by "`or`" to remove the conditional jump. The code should be more efficient.
